### ISSUE TITLE
kindle 版本无法构建

### ISSUE THREAD

**Issue by chloerei** [ruby-china/rails-guides#84]
```
$ docker run -it -v $(pwd):/app rails-guides rake guides:generate:kindle
/usr/local/bin/ruby rails_guides.rb
Generating 3_0_release_notes.md as 3_0_release_notes.html
Generating 3_1_release_notes.md as 3_1_release_notes.html
Generating 3_2_release_notes.md as 3_2_release_notes.html
Generating 4_0_release_notes.md as 4_0_release_notes.html
Generating 4_1_release_notes.md as 4_1_release_notes.html
Generating 4_2_release_notes.md as 4_2_release_notes.html
Generating 5_0_release_notes.md as 5_0_release_notes.html
US-ASCII
/app/rails_guides/markdown/renderer.rb:34:in `paragraph': invalid byte sequence in US-ASCII (ArgumentError)
	from /app/rails_guides/markdown.rb:78:in `render'
	from /app/rails_guides/markdown.rb:78:in `generate_body'
	from /app/rails_guides/markdown.rb:22:in `render'
	from /app/rails_guides/generator.rb:163:in `block in generate_guide'
	from /app/rails_guides/generator.rb:142:in `open'
	from /app/rails_guides/generator.rb:142:in `generate_guide'
	from /app/rails_guides/generator.rb:91:in `block in generate_guides'
	from /app/rails_guides/generator.rb:89:in `each'
	from /app/rails_guides/generator.rb:89:in `generate_guides'
	from /app/rails_guides/generator.rb:37:in `generate'
	from rails_guides.rb:20:in `<main>'
rake aborted!
Command failed with status (1): [/usr/local/bin/ruby rails_guides.rb...]
/app/rakefile:22:in `block (3 levels) in <top (required)>'
/app/rakefile:35:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => guides:generate:html
(See full trace by running task with --trace)
```

不知哪一步把 body 弄成了 US-ASCII 编码，有空再查。

**Comment by AndorChen** [comment]
我更新了一下 `kindle` 任务（#85），在本地测试没遇到问题。

ps 我没用 Docker
